### ISSUE TITLE
Awesome books: with ES6

### ISSUE THREAD

**Issue by Sparktan24** [fmanimashaun/Awesome-book_es6#2]
Good job so far! The project looks good. 
There is a couple of details, to follow the ES6 best practices we should use arrow functions. And as an optional observation, maybe you can take advantage of the luxon library to save some code and use:

`const dt = DateTime.now();`
`document.getElementById('yourHTMLID').innerHTML = dt.toLocaleString(DateTime.DATETIME_MED);`
This should give you the actual date in the required format.

Cheers!

**Comment by fmanimashaun** [comment]
> toLocaleString(DateTime.DATETIME_MED);

Actually, it will give you in the following format:  `8 Nov 2022, 8:49 pm` but based on the project requirements, we need to return the date and time in ` November 8th 2022, 8:51:2 PM` See the image below:
![](https://raw.githubusercontent.com/microverseinc/curriculum-javascript/main/books/images/awesome_books_full_website.png?token=GHSAT0AAAAAAB2Y7VT5TBUBUC4LFR4FD6R2Y3KYHMQ)

Based on my research, luxon doesn't support putting `st`. `nd`, `rd` or `th`, I came across the following:

1. https://github.com/moment/luxon/issues/118

Thus, luxon doesn't support it directly, thus, I had to improvise
